### ISSUE TITLE
Виконайте опис предметної області

### ISSUE THREAD

**Issue by kolgenpav** [ESEI-ZNU/Calculator#1]
Надіслати звіт,, шаблон якого знаходиться на сторінці дисципліни в Moodle, у якому привести опис предметної області проекту, включаючи основні поняття, класифікацію та детальний опис алгоритмів (методів) вирішення завдань та засоби (інструменти), які планується використати (кожен учасник команди наводить однаковий (копію) загальний опис предметної області, включаючи основні поняття, класифікацію, перелік алгоритмів (методів), інструментів вирішення завдань та детальний опис предметної області, алгоритмів (методів), інструментів вирішення своїх завдань в рамках виконання проекту).

**Comment by kolgenpav** [comment]
Зауваження до Вікі:
1.  Замість заголовка **Теоретичні відомості** введіть **Основні визначення**
2. Видаліть заголовок **Опис предметної області** після **Завдання** і те що в ньому - визначення консольного калькулятора - це вже було на початку.
3. З розділу **Виконання роботи** видаліть перші два речення.
4. Додайте у розділ Виконання роботи підрозділ **Алгоритм перетворення виразу у постфіксну форму** і описуйте алгоритм у цьому підрозділі
5. Відредагуйте список дій у описі алгоритму, щоб елементи ненумерованого списку були з нового рядка
6. Додайте у розділ Виконання роботи підрозділ Переведення чисел з десяткової системи до двійкової та шістнадцяткової і робіть опис у цьому підрозділі
7. Наведіть приклад переведення довільного десяткового чила у двійкове
8.. Наведіть приклад переведення довільного десяткового чила у шістнадцяткове
9. Додайте до опису таблицю, яка є у Вашому звіті

**Comment by DanyloBoleyko** [comment]
Виправив зауваження до Вікі
